[package]
name = "quadcopter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapier3d = { version = "0.17.1", features = [ "simd-stable" ] }
kiss3d = "0.35.0"
nalgebra = "0.32.1"
gilrs = "0.10.1"
